### ISSUE TITLE
Attempting to play back the recording drops the call. "Error processing media request" 

### ISSUE THREAD

**Issue by EvanDaley** [Bandwidth/examples#73]
I'm attempting to play back voicemails based on this example: https://github.com/Bandwidth/examples/blob/master/ruby/RecordingApp/app.rb

I can't seem to get this bit to work. After I send this BXML to bandwidth, the phone call is immediately **dropped**. 

```
play_recording = Bandwidth::Voice::PlayAudio.new({
    :url => data["tag"],
    :username => VOICE_API_USERNAME,
    :password => VOICE_API_PASSWORD
})
response.push(play_recording)
```

This is the raw BXML that I'm sending, and I think it looks fine.

```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <PlayAudio username="[REDACTED]" password="[REDACTED]">
    https://voice.bandwidth.com/api/v2/accounts/[REDACTED]/calls/c-6a0d8e3e-a08bea47-fb75-40a0-a450-cd72e67c88c6/recordings/r-fbe17a78-e4e7ea0c-6692-446a-82a6-06e631a82877/media
  </PlayAudio>
  <Gather gatherUrl="http://abe582a0145b.ngrok.io/bandwidth/callback/redirect-to-voicemail-if-applicable" maxDigits="1">
    <SpeakSentence>Would you like to re record? Press 1 if so, otherwise please hangup</SpeakSentence>
  </Gather>
</Response>
```

Other important pieces of context:

- I **am** able to access the media in chrome with the same username/password at that exact URL, so I know the media is accessible. 
- I'm using the `recording_available_url` hook, which bandwidth is triggering before I attempt to access the media.
- Playing other media is fine (e.g. `beep-01a.wav` from this example works).
- If I look up the metadata for the call I'm able to see: **"Error processing media request"**. 
- I'm using version 3.12.1 of `bandwidth-sdk`

**Comment by ajrice6713** [comment]
Hey Evan,

Do you know if the recording is available yet? What I imagine is happening is that Bandwidth is returning a 404 to itself when we try to stream the media from your media URL if it has not finished processing yet - are you confirming this with a recording available callback? 

Otherwise, if that isnt the case, would you mind opening up a ticket through [support.bandwidth.com](support.bandwidth.com) and providing me with the ticket #, I can get some more information from you that way and we can troubleshoot from there!

**Comment by EvanDaley** [comment]
Hey AJ, thanks for the quick response.

Here is the ticket number from support.bandwidth: #3775466

Yes I followed the same methodology as the example. I start recording with `Bandwidth::Voice::Record` and provide a `recording_available_url`. As soon as the recording is available, bandwidth triggers a callback which I use to trigger the next prompt. After that, if the user presses a 1 to hear the recording, the caller is sent a route like `/EndGather1` from this example: https://github.com/Bandwidth/examples/blob/master/ruby/RecordingApp/app.rb

**Comment by EvanDaley** [comment]
Hey AJ, thanks for your follow up email. 

For anyone else that runs into this: the problem is that they block their internal IPs from being accessed by the PlayAudio request. Their suggestion is to download the media, host it somewhere, and then use PlayAudio to access the file from your own server.
