### ISSUE TITLE
Issue with WebRTC (no audio)

### ISSUE THREAD

**Issue by EvanDaley** [Bandwidth/examples#76]
Both node webrtc examples are unable to communicate audio in either direction.

This is the one that I have running right now:
https://github.com/Bandwidth/examples/tree/master/nodejs/webrtc-hello-again

- I updated my env with the appropriate credentials/ngrok url.
- The example successfully initiates a phone call.
- onStreamAvailable is triggered once the call is answered.
- The call is active on both ends 
- If I try to send audio in either direction nothing happens (only silence).

Help!

**Comment by ajrice6713** [comment]
Hey Evan,

There was an update to the bundle file to address a bug like this - would you mind running the attached version of the example and let me know if you are successful? 

[webrtc-hello-again.zip](https://github.com/Bandwidth/examples/files/5777041/webrtc-hello-again.zip)

**Comment by EvanDaley** [comment]
Looks like that doesn't work either. 

node server.js
```
Example app listening on port  http://localhost:3000
setup browser client
No session found, creating one
Failed to create session: { errorMessage: 'Unauthorized',
  errorCode: 401,
  errorResponse:
   '{"error": "Unable to authenticate, credentials missing or invalid", "requestId": "682e15d2-2288-48f5-bc55-9e8ec6a7bc5d"}' }
Failed to start the browser call: Error: Error in createSession, error from BAND:Unauthorized
    at getSessionId (/Users/hannakalesnikava/code/webrtc-hello-again-2/server.js:180:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

We are using these three fields for authentication and the authentication was working with the original javascript bundle.
```
ACCOUNT_ID
USERNAME
PASSWORD
```

**Comment by ajrice6713** [comment]
Hey Evan,

We just published a new version about an hour ago - can you pull a fresh clone of the repo again and try that? 

If we are still unable to get this resolved I might have you open a support ticket within our support system and work from there, as I am unable to replicate the issue. I might need to take a look at your account configuration.

**Comment by EvanDaley** [comment]
Thanks AJ, I'll give that a shot and get back to you!

**Comment by EvanDaley** [comment]
No luck. Same issue. Ticket number: #3797126
